; HEADER_BLOCK_START
; generated by OrcaSlicer 2.0.0 on 2024-04-09 at 19:26:15
; total layer number: 673
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 134.60
; HEADER_BLOCK_END

; external perimeters extrusion width = 0.63mm
; perimeters extrusion width = 0.66mm
; infill extrusion width = 0.66mm
; solid infill extrusion width = 0.66mm
; top infill extrusion width = 0.60mm
; first layer extrusion width = 0.63mm

; EXECUTABLE_BLOCK_START
M73 P0 R249
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M140 S60 ; set final bed temp
M104 S170 ; set temporary nozzle temp to prevent oozing during homing and auto bed leveling
G4 S10 ; allow partial nozzle warmup
G28 ; home all axis
